# Generated by Django 4.1.7 on 2023-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(max_length=255, verbose_name="Organization"),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Grade",
            new_name="Staff_user",
        ),
        migrations.DeleteModel(
            name="Work_place",
        ),
        migrations.RenameField(
            model_name="staff_user",
            old_name="position",
            new_name="staff",
        ),
    ]
