# Generated by Django 4.1.7 on 2023-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_organizations_rename_grade_staff_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pinfl",
            field=models.CharField(max_length=50, unique=True, verbose_name="JSHSHR"),
        ),
    ]
