# Generated by Django 4.1.7 on 2023-06-01 18:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_customuser_pinfl"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizations",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizations",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizations",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="account.organizations",
            ),
        ),
        migrations.AddField(
            model_name="organizations",
            name="rght",
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizations",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organizations",
            name="organization",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Organization"
            ),
        ),
    ]
