# Generated by Django 4.1.7 on 2023-06-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_organizations_level_organizations_lft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="organizations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="account.organizations",
            ),
        ),
    ]
