# Generated by Django 5.0.2 on 2024-02-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_staff_user_staff_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.staff_user'),
        ),
    ]
