# Generated by Django 4.1.7 on 2023-03-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_text_alter_question_text_and_more'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='quiz.category'),
        ),
    ]
