# Generated by Django 4.1.7 on 2023-03-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_level_remove_course_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
