# Generated by Django 4.1.7 on 2023-04-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_alter_question_uuid"),
        ("course", "0004_file_image_text_video_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="quiz.category",
            ),
        ),
    ]
