# Generated by Django 4.1.7 on 2023-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_alter_module_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
