# Generated by Django 4.1.7 on 2023-06-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0020_alter_question_uuid"),
        ("course", "0007_alter_file_title_alter_image_title_alter_text_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                related_query_name="courses",
                to="quiz.category",
            ),
        ),
    ]
