# Generated by Django 4.1.7 on 2023-03-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Required and unique', max_length=255, verbose_name='Category Name'),
        ),
    ]
