# Generated by Django 4.1.7 on 2023-03-10 11:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, help_text="Bo'limni tanlang", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='quiz.category', verbose_name="Bo'lim"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(blank=True, verbose_name='Test savollari soni'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_to_pass',
            field=models.IntegerField(help_text="O'tish uchun eng past ball ms: ( 71 )", verbose_name="o'tish bali"),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
