# Generated by Django 4.1.7 on 2023-03-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_file_image_text_video_alter_module_options_and_more'),
        ('quiz', '0003_alter_answer_text_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='course.course'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='course.module', verbose_name='module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score_to_pass',
            field=models.IntegerField(help_text="O'tish uchun eng past ball (1 ~ 100 oralig'ida)", verbose_name="o'tish bali"),
        ),
    ]
