# Generated by Django 4.1.7 on 2023-03-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_file_image_text_video_alter_module_options_and_more'),
        ('quiz', '0004_quiz_course_quiz_module_alter_quiz_score_to_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.module', verbose_name='module'),
        ),
    ]
