# Generated by Django 4.1.7 on 2023-03-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_file_image_text_video_alter_module_options_and_more'),
        ('quiz', '0005_alter_quiz_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['category', 'course', 'module']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='course.module', verbose_name='module'),
        ),
    ]
