# Generated by Django 4.1.7 on 2023-03-25 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_options_alter_quiz_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('297be442-1eaa-4e3f-901c-7ed03882f6c6'), editable=False),
        ),
    ]
