# Generated by Django 4.1.7 on 2023-04-25 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0007_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("1866fe90-7e5c-4658-b9a1-fbc3b0a230f8"),
                editable=False,
                unique=True,
            ),
        ),
    ]
