# Generated by Django 4.1.7 on 2023-04-25 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("56d594da-7acc-49c9-ab76-529084182c62"),
                editable=False,
                unique=True,
            ),
        ),
    ]
