# Generated by Django 4.1.7 on 2023-05-18 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0009_alter_question_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(default=0, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("40b2759e-c272-48e6-bdef-c034924fab14"),
                editable=False,
                unique=True,
            ),
        ),
    ]
