# Generated by Django 4.1.7 on 2023-05-19 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0011_result_date_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("ae04fc94-5855-4a09-88d2-d9321e6a8db1"),
                editable=False,
                unique=True,
            ),
        ),
    ]
