# Generated by Django 4.1.7 on 2023-05-21 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0012_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("295cb1b1-1c4c-40ef-a309-5d2b8b98a093"),
                editable=False,
                unique=True,
            ),
        ),
    ]
