# Generated by Django 4.1.7 on 2023-05-28 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_subject"),
        ("quiz", "0013_alter_question_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExcelFileUploaded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excel_file", models.FileField(upload_to="excel")),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("c859ac01-fb96-44c7-8b3a-f2964fe4af72"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizs_course",
                to="course.course",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizs_module",
                to="course.module",
                verbose_name="module",
            ),
        ),
    ]
