# Generated by Django 4.1.7 on 2023-06-01 18:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0015_alter_excelfileuploaded_excel_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("6d747e30-99db-45d1-969c-49d9dba08f32"),
                editable=False,
                unique=True,
            ),
        ),
    ]
