# Generated by Django 4.1.7 on 2023-06-05 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0016_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9a8abcdc-b08d-4504-8371-536e0f570337"),
                editable=False,
                unique=True,
            ),
        ),
    ]
