# Generated by Django 4.1.7 on 2023-06-22 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0018_result_update_date_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("83ffd3a3-d4fc-4c60-9845-fa48878c7369"),
                editable=False,
                unique=True,
            ),
        ),
    ]
