# Generated by Django 4.1.7 on 2023-06-24 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0019_alter_question_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("b5de2465-6a1e-483a-bb3c-f64004162770"),
                editable=False,
                unique=True,
            ),
        ),
    ]
