# Generated by Django 5.0.2 on 2024-02-12 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_quiz_owner_alter_question_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0ebad9f4-5b6e-43fc-8517-2807e447a472'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, choices=[('yk', 'Yakuniy nazorat'), ('st', 'Sinov test')], default='yk', max_length=255, verbose_name='Sarlavha'),
        ),
    ]
